name: Deploy to iNet Hosting

# Kịch bản này sẽ chạy khi có lệnh PUSH lên nhánh main
on:
  push:
    branches:
      - main # Nếu nhánh của bạn tên là 'master', hãy đổi 'main' thành 'master'

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Lấy code mới nhất từ GitHub
      uses: actions/checkout@v4

    - name: Đồng bộ file qua FTP lên iNet
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: / # Lưu ý đọc giải thích bên dưới về dòng này
        exclude: |
          **/.git*
          **/.git*/**
          **/.github/**
          README.md
          .gitignore
